name: Update Version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Increment version in JSON file
      run: |
        VERSION_FILE=version.json
        echo "Current version file content:"
        cat $VERSION_FILE
        VERSION=$(jq .version $VERSION_FILE)
        echo "Current version is $VERSION"
        NEW_VERSION=$((VERSION + 1))
        echo "New version is $NEW_VERSION"
        jq --arg new_version "$NEW_VERSION" '.version=($new_version | tonumber)' $VERSION_FILE > temp.json && mv temp.json $VERSION_FILE
        echo "Updated version file content:"
        cat $VERSION_FILE

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add version.json
        git commit -m "Increment version to $NEW_VERSION"
        git push
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
