name: Increment Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Increment version number
        id: increment_version
        run: |
          VERSION=$(jq -r '.version' version.json)
          NEW_VERSION=$((VERSION + 1))
          echo "New version: $NEW_VERSION"
          echo "{\"version\": $NEW_VERSION}" > version.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add version.json
          git commit -m "Increment version to $NEW_VERSION"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
